### ISSUE TITLE
Ubuntu 1804 Beta 2 - Grub Failed

### ISSUE THREAD

**Issue by Morantz** [stockmind/gpd-pocket-ubuntu-respin#117]
I have tried install with & without internet connected and can't get grub2 to install on my GPD Pocket.

Is there a workaround?  Can you force the updated installer into the respin?

My Respin was build with the gnome and bioticbeaver switches with the Beta 2 ISO as input.

**Comment by stockmind** [comment]
This seems to be a common issue and we first need to identify where the problem is and what is causing the grub install or update failure

**Comment by roelandp** [comment]
Was it related to https://bugs.launchpad.net/ubuntukylin/+bug/1767067 bug which was fixed yesterday before the release?

**Comment by Morantz** [comment]
Tried building again with the release ISO and the resulting image fails to install at : 
<code>
Running /scripts/casper-premount ...  done.

done.

busybox blah blah blah   then

(initramfs) Unable to find a medium containing a live file system
</code>

The image is written to the same flash key use before (and to reinstall 17.10 after its' failure..)
I also ran ./clean.sh and then rebuilt the image, then rewrote it to the flash key using etcher, same as all other installs....
-edited for formatting...

**Comment by roelandp** [comment]
@Morantz I am new to gpd pocket. I had that very same bug as well with my USB stick. But I had it too with @stockmind 's ISO. I opted for using an SD card installation instead. 

Does that error just above it also indicated something like: 'Found slow USB' or something? 

For me the installation of 17.1 was pretty using the solution with an sd card (couldnt find any other usb sticks at home :P) . will try asap with 18.4 too and let you know. Maybe you could try with another usb / sd card maybe?

**Comment by octarect** [comment]
@Morantz Hi, there. I also tried to install 18.04 on my GPD Pocket, and it's failed with the following error;

```
The 'grub-efi-amd64-signed' package failed to install into /target/.
```

Is this same as your problem?

By the way, I thought that it was related to https://askubuntu.com/questions/789998/16-04-new-installation-gives-grub-efi-amd64-signed-failed-installation-target.
 I have already tried the solution which is mentioned in the URL (manually partitioning), but I have still the error.

**Comment by JunSaitoJP** [comment]
Try it.
1. Boot Live Ubuntu after Ubuntu installed.
2. sudo add-apt-repository ppa:yannubuntu/boot-repair && sudo apt-get update
3. sudo apt-get install -y boot-repair && (boot-repair &)
4. Click Recommended repair

**Comment by stockmind** [comment]
Can you all check if you get this in your `/var/log/syslog` after install?

```
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to register the boot entry: No such file or directory.
```

I should have time in the next days to test a clean install.

**Comment by octarect** [comment]
@stockmind Yes, I found them in my /var/log/syslog after installation failure.
(Testing Ubuntu 18.04, and Xubuntu 18.04)

```
EFI variables are not supported on this system.
grub-install: error: efibootmgr failed to register the boot entry: No such file or directory.
dpkg: error processing package grub-efi-amd64-signed (--configure)
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 grub-efi-amd64-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by Morantz** [comment]
I have the same messages as octarect above.  Also about 2 pages up I have the following lines:
`     System not running in EFI mode, not installing to EFI system partition.`
`     EFI variables are not supported on this system.`
 Not sure if the above is important or not....

**Comment by Morantz** [comment]
Also, I am not sure why, but it took me 7 build attempts to get an image that doesn't die with the:
(initramfs) Unable to find a medium containing a live file system
error....  (And those failed image don't work on ANY system.  I tried a desktop, normal laptop and GPD.)

**Comment by Morantz** [comment]
After my latest failed install of 18.04, I followed JunSaitoJP's instructions above.  I got a system that now boots, but isn't correctly installed.  (Installer is still installed, ect...)
I did the git thing and ran: `./update.sh gnome bionicbeaver`
After a reboot, it takes a while for the login manager to startup.  (Like a minute or so?)  Looks ok after that.

**Comment by Morantz** [comment]
The login manager issue is related to using a 4.17 kernel and LightDM.

**Comment by Xunius** [comment]
I got the same error as reported by @octarect when trying to install Ubuntu-MATE 18.04, and @JunSaitoJP 's method worked for me.

**Comment by stockmind** [comment]
I'm uploading two new 18.04.1 ISOs, GNOME and UNITY with 4.18-rc8 mainline kernel and updated packages (grub included). 
Reinstalled system through the new GNOME iso and grub installed correctly as expected without issues.
Let me know.
System seems stable. :)

EDIT: It seems it takes long to boot sometimes, i'm checking it.

**Comment by Morantz** [comment]
I am very glad to hear this has been corrected.  I will be traveling out of state for a couple days and will try this when I get back.  Thanks @stockmind !!

**Comment by bradcosine** [comment]
@stockmind I'm still having the same issue where install fails with error `The 'grub-efi-amd64-signed' package failed to install into /target/.` 

Using these ISOs on GPD Pocket 1. Are there any additional steps needed other than booting from ISO on USB? Thanks in advance for your help.

gpdpocket-gnome-20180912-4.18.0-rc8-ubuntu-18.04.1-desktop-amd64.iso
gpdpocket-unity-20180912-4.18.0-rc8-ubuntu-18.04.1-desktop-amd64.iso

edit: working on a fix, will report back if it works.

**Comment by bradcosine** [comment]
I had to used [boot-repair](https://help.ubuntu.com/community/Boot-Repair) and was able to resolve my issue:
```
sudo add-apt-repository ppa:yannubuntu/boot-repair
sudo apt-get update
sudo apt-get install -y boot-repair && boot-repair
```

**Comment by Morantz** [comment]
I thought he said those ISOs had been fixed.  I haven't had time to reload mine in a while...  I also use the boot-repair method listed by bradcosine above.

**Comment by bradcosine** [comment]
I'm experiencing the long boot time that @Morantz reported.. I look forward to hearing what you find on this @stockmind .. thanks.

**Comment by stockmind** [comment]
Ok this is odd, if i respin ISO with mainline kernel everything (grub) seems to install fine but boot times seems to be unbearable, if i respin ISO with hans kernel grub stop to install correctly ... mhmh

**Comment by luzhuomi** [comment]
I just tried today. Facing the exact issue.

**Comment by muchweb** [comment]
I just had installation GRUB error with pre-respun `ubuntu-gnome 18.04` on first Pocket. Then I rebooted to liveCD again and run `boot-repair` script. This fixed it for me (installed system booted successfully).

**Comment by luzhuomi** [comment]
> I just had installation GRUB error with pre-respun `ubuntu-gnome 18.04` on first Pocket. Then I rebooted to liveCD again and run `boot-repair` script. This fixed it for me (installed system booted successfully).

Thanks. I did that and it works. =)

**Comment by rpwhite3** [comment]
I was able to load the current version, got the GRUB ERROR, did the boot-repair all is good... I think it takes a few extras to start up but works like a charm.  I haven't used my GPD for months as a update along the way borked it, but now all good... thanks!  Going to use it for my python development machine...

**Comment by qzhuyan** [comment]
I managed to repair manually after installation process crash. (no restart)


```
sudo mount /dev/sdXXX /mnt
sudo mount /dev/sdXY /mnt/boot
sudo mount /dev/sdXX /mnt/boot/efi
for i in /dev /dev/pts /proc /sys /run /sys/firmware/efi/efivars; do sudo mount -B $i /mnt$i; done
sudo chroot /mnt
grub-install /dev/sdX
update-grub 
```

where 
- /dev/sdXXX is root partition
- /dev/sdXY is boot partition
- /dev/sdXX is EFI partition
- /dev/sdX is disk
   
I think the trick is mount efivars to tmp root before chroot.

reference: 
https://unix.stackexchange.com/questions/91620/efi-variables-are-not-supported-on-this-system
https://askubuntu.com/questions/831216/how-can-i-reinstall-grub-to-the-efi-partition

**Comment by hoonsubin** [comment]
The repair-boot method did not work for me, so I tried @qzhuyan's method (one mentioned [here](https://askubuntu.com/questions/831216/how-can-i-reinstall-grub-to-the-efi-partition) to be precise), and I managed to make my Ubuntu 19.10 eoan to boot successfully.
One thing to note was that when running `grub-install /dev/sdX`, it shows a couple of `no such directories or files` error, but in my case, I just ignored it and executed `update-grub`. Now it all works well, thanks.
